# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PVAmplitudeDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PVAmplitudeDemo
  pod 'Amplitude-iOS', '~> 4.0.4'

  target 'PVAmplitudeDemo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PVAmplitudeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
