# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "3f9afd0d-c990-4c7a-bf58-e625b3b4abb9"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  cocoapods

  increment_build_number

  cert
  sigh
  
  # build your iOS app
  gym(
    workspace: "PVAmplitudeDemo.xcworkspace",
    scheme: "PVAmplitudeDemo",
    export_method: "ad-hoc"
  )

  # upload to Testflight
  #pilot(
  #  skip_waiting_for_build_processing: true,
  #  skip_submission: true,
  #  username: "keith@gittie.com",
  #  app_identifier: "com.gittie.pvamplitudeexercise"
  #)
end
